<?php
namespace MCris112\FileSystemManager\Resources\FmFile;

use Illuminate\Http\Resources\Json\ResourceCollection;

class FmFileListCollection extends ResourceCollection
{

    public function toArray(\Illuminate\Http\Request $request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}
